---

- name: Install clang formatter
  apt:
    name: clang-format
    state: latest
  become: true

- name: Install python formatter (step 1/3)
  pip:
    name: yapf
    executable: pip3
  become: true

- name: Install python formatter - Make yapf config dir (step 2/3)
  file:
    path: ~/.config/yapf
    state: directory

- name: Install python formatter - Create yapf default config symbolic link (step 3/3)
  file:
    src: "{{ playbook_dir }}/rc/yapf_config"
    dest: ~/.config/yapf/style
    state: link

- name: Install shell formatter
  shell: zsh -c ". ~/.zshrc && go get mvdan.cc/sh/cmd/shfmt"

- name: Install js formatter
  npm:
    name: js-beautify
    global: yes
  become: true
