---
- name: Install Node.js - Add apt repository for Node.js (1/2)
  shell: "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -"

- name: Install Node.js - Install Node.js package (step 1/2)
  apt:
    name: nodejs
    state: latest
  become: true

